name: First sample

on:
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: MyApp
      APP_VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v4

      - name: Show env variables
        run: |
          echo "App Name: $APP_NAME"
          echo "App Version: $APP_VERSION"

      - name: Use both together
        run: echo "Running $APP_NAME version $APP_VERSION"
