name: First sample

on:
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]
 

jobs:
  build:
    runs-on: windows-latest  # ← changed from ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create a file
        run: echo "This is my artifact" > myfile.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: myfile.txt

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Show the file
        run: cat myfile.txt
