name: My First Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Say hello
        run: echo "Hello from Pavan!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
